### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [cravend/theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, please consider renaming it to something less generic than `theme`.

Thanks!

**Comment by cravend** [comment]
Awesome, glad to hear it! I'll add some screenshots to both this + [autodark](https://github.com/cravend/autodark) — I created them to go together (and I didn't expect there to be attention on them already!).

**Comment by cravend** [comment]
Screenshots have been added! I haven't settled on a new name yet.

**Comment by unixorn** [comment]
Cool, update this issue when you do (or just PR it into https://github.com/unixorn/awesome-zsh-plugins/ if you want) and I'll get it added.
